CREATE TABLE "paciente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_paciente" varchar(50),
  "data_nascimento" date,
  "email_paciente" varchar(50) UNIQUE,
  "cpf_paciente" char(11) UNIQUE NOT NULL,
  "rg_paciente" varchar(25) UNIQUE,
  "id_endereco" int,
  "id_convenio" int,
  "num_carteira" varchar(50)
);

CREATE TABLE "convenio" (
  "id" int PRIMARY KEY,
  "nome_convenio" varchar(50),
  "cnpj_convenio" CHAR(14),
  "tempo_carencia" int(30)
);

CREATE TABLE "endereco" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cep" int(10),
  "rua" varchar(50),
  "bairro" varchar(50),
  "cidade" varchar(50),
  "estado" varchar(50)
);

CREATE TABLE "telefone_paciente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_pais" int(3),
  "ddd" int(2),
  "numero" int(10),
  "id_paciente" int
);

CREATE TABLE "telefone_medico" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo_pais" int(3),
  "ddd" int(2),
  "numero" int(10),
  "id_medico" int
);

CREATE TABLE "medico" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_medico" varchar(50),
  "crm_medico" VARCHAR(20) UNIQUE NOT NULL,
  "cpf_medico" char(11) UNIQUE NOT NULL,
  "email_medico" varchar(50),
  "id_cargo" int,
  "id_endereco" int
);

CREATE TABLE "cargo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_cargo" varchar(50)
);

CREATE TABLE "MedicoEspecialidade" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_medico" int,
  "id_especialidade" int
);

CREATE TABLE "especialidade" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_especialidade" varchar(50)
);

CREATE TABLE "Consulta" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_paciente" int,
  "id_medico" int,
  "data_consulta" date,
  "hora_consulta" time,
  "valor_consulta" decimal(10,2),
  "id_convenio" int
);

CREATE TABLE "receita" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_consulta" int
);

CREATE TABLE "ReceitaMedicamento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_receita" int,
  "id_medicamento" int,
  "qtd_medicamento" int,
  "instrucoes_medicamento" varchar(200)
);

CREATE TABLE "Medicamento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_medicamento" varchar(50)
);

CREATE TABLE "Internacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "data_entrada" date,
  "data_prev_alta" date,
  "data_alta" date,
  "procedimento" varchar(200),
  "id_quarto" int,
  "id_medico" int,
  "id_paciente" int
);

CREATE TABLE "Quarto" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "num_quarto" int(2),
  "id_tipo_quarto" int
);

CREATE TABLE "TipoQuarto" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descricao" varchar(50),
  "valor_diaria" decimal(10,2)
);

CREATE TABLE "InternacaoEnfermeiro" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_internacao" int,
  "id_enfermeiro" int
);

CREATE TABLE "Enfermeiro" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome_enfermeiro" varchar(50),
  "cpf_enfermeiro" char(11) UNIQUE NOT NULL,
  "coren" varchar(50)
);

ALTER TABLE "paciente" ADD FOREIGN KEY ("id_endereco") REFERENCES "endereco" ("id");

ALTER TABLE "paciente" ADD FOREIGN KEY ("id_convenio") REFERENCES "convenio" ("id");

ALTER TABLE "telefone_paciente" ADD FOREIGN KEY ("id_paciente") REFERENCES "paciente" ("id");

ALTER TABLE "telefone_medico" ADD FOREIGN KEY ("id_medico") REFERENCES "medico" ("id");

ALTER TABLE "medico" ADD FOREIGN KEY ("id_cargo") REFERENCES "cargo" ("id");

ALTER TABLE "medico" ADD FOREIGN KEY ("id_endereco") REFERENCES "endereco" ("id");

ALTER TABLE "MedicoEspecialidade" ADD FOREIGN KEY ("id_medico") REFERENCES "medico" ("id");

ALTER TABLE "MedicoEspecialidade" ADD FOREIGN KEY ("id_especialidade") REFERENCES "especialidade" ("id");

ALTER TABLE "Consulta" ADD FOREIGN KEY ("id_paciente") REFERENCES "paciente" ("id");

ALTER TABLE "Consulta" ADD FOREIGN KEY ("id_medico") REFERENCES "medico" ("id");

ALTER TABLE "Consulta" ADD FOREIGN KEY ("id_convenio") REFERENCES "convenio" ("id");

ALTER TABLE "receita" ADD FOREIGN KEY ("id_consulta") REFERENCES "Consulta" ("id");

ALTER TABLE "ReceitaMedicamento" ADD FOREIGN KEY ("id_receita") REFERENCES "receita" ("id");

ALTER TABLE "ReceitaMedicamento" ADD FOREIGN KEY ("id_medicamento") REFERENCES "Medicamento" ("id");

ALTER TABLE "Internacao" ADD FOREIGN KEY ("id_quarto") REFERENCES "Quarto" ("id");

ALTER TABLE "Internacao" ADD FOREIGN KEY ("id_medico") REFERENCES "medico" ("id");

ALTER TABLE "Internacao" ADD FOREIGN KEY ("id_paciente") REFERENCES "paciente" ("id");

ALTER TABLE "Quarto" ADD FOREIGN KEY ("id_tipo_quarto") REFERENCES "TipoQuarto" ("id");

ALTER TABLE "InternacaoEnfermeiro" ADD FOREIGN KEY ("id_internacao") REFERENCES "Internacao" ("id");

ALTER TABLE "InternacaoEnfermeiro" ADD FOREIGN KEY ("id_enfermeiro") REFERENCES "Enfermeiro" ("id");
